apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.mistral.model.name }}-access
  namespace: {{ .Values.namespaces }}
  labels:
    opendatahub.io/dashboard: "true"
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    resourceNames: [{{ .Values.mistral.model.name | quote }}]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.mistral.model.name }}-access
  namespace: {{ .Values.namespaces }}
  labels:
    opendatahub.io/dashboard: "true"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.mistral.model.name }}-sa
    namespace: {{ .Values.namespaces }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.mistral.model.name }}-access

