{{- if .Values.whisper.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.whisper.model.name }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    openshift.io/display-name: "Whisper Large V3"
    opendatahub.io/model-name: {{ .Values.whisper.model.name | quote }}
{{- end }}

