apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mistral.model.name }}-sa
  namespace: {{ .Values.namespaces }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    openshift.io/display-name: {{ .Values.mistral.model.displayName | quote }}
    opendatahub.io/model-name: {{ .Values.mistral.model.name | quote }}

