apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.whisper.model.name }}-sa-token
  namespace: {{ .Values.namespaces }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    kubernetes.io/service-account.name: {{ .Values.whisper.model.name }}-sa
    openshift.io/display-name: "Whisper Large V3"
    opendatahub.io/model-name: {{ .Values.whisper.model.name | quote }}
type: kubernetes.io/service-account-token

